before_script:
    - apt-get install brew
    - brew install python3 
    - python3 -V

stages:
    - build
    - test

build:
    stage: build
    tags:
        - osx
    script:
        - make

test:
    stage: test
    tags:
        - osx
        - python3
    script:
        - python3 run_test.py
    coverage: /TOTAL\s+\d+\s+\d+\s+(\d+)%$/
