stages:
    - build
    - test

build:
    stage: build
    tags:
        - osx
    script:
        - make

test:
    stage: test
    tags:
        - osx
    script:
        - make
        - ./test_ssl.sh
